(define (problem p)
 (:domain dir2)
 (:objects wp0 wp1 wp2 wp3 wp4 wp5 wp6 wp7 wp8 - waypoints)
 (:init
  (robot_at wp8)
  (obstacle wp2)(obstacle wp3)(obstacle wp4)
  (grid wp0)(grid wp1)(grid wp2)(grid wp3)(grid wp4)(grid wp5)(grid wp6)(grid wp7)(grid wp8)
  (connected wp0 wp3)
  (connected wp0 wp1)
  (connected wp1 wp4)
  (connected wp1 wp0)
  (connected wp1 wp2)
  (connected wp2 wp5)
  (connected wp2 wp1)
  (connected wp3 wp0)
  (connected wp3 wp6)
  (connected wp3 wp4)
  (connected wp4 wp1)
  (connected wp4 wp7)
  (connected wp4 wp3)
  (connected wp4 wp5)
  (connected wp5 wp2)
  (connected wp5 wp8)
  (connected wp5 wp4)
  (connected wp6 wp3)
  (connected wp6 wp7)
  (connected wp7 wp4)
  (connected wp7 wp6)
  (connected wp7 wp8)
  (connected wp8 wp5)
  (connected wp8 wp7)
 )
 (:goal (and (visited wp5) ))
)